.\Man page for Inodeum
.TH Inodeum 1 2018-05-16
.SH NAME
Inodeum \- A ISP internet usage monitor (plus more) for Internode.
.SH SYNOPSIS
.B Inodeum
.SH DESCRIPTION
\fBInodeum\fRis a Linux application to view internet data usage for Internode
users. It also allows for historical usage examination and indicates current 
network performance.
.SH OPTIONS
Inodeum has no options.
.SH EXIT STATUS
On success Inodeum will exit(0); on error it will exit(-1). Further details will
be in the log file.
.SH FILES
.TP
$HOME/.Inodeum/Inodeum.log 
Logs all messages, errors, events (viewable in GUI)
.TP
$HOME/.Inodeum/user_preferences
Application preferences (set up in GUI)
.SH BUGS
Pleas report bugs to the author. 
.SH AUTHOR
Inodeum and this manual page were written by Anthony Buckley <tony.buckley000@gmail.com>
